#!/bin/bash

DIR=$(mktemp -d)
REMOTE=$1
BACKUP_PATH=$2

SERVICES_TO_STOP=("pihole" "mariadb")

pre_backup() {
  for service in "${SERVICES_TO_STOP[@]}"; do
    docker stop $service
  done
}

cleanup() {
  cd /tmp/ # You can't umount or rm a directory while you are in it.
  for m in /dev/ /tmp/ /var/log/ /boot/ /; do
    sudo umount ${DIR}${m}
  done
  rm -rf ${DIR}
}

do_mounts() {
  sudo mount /dev/mmcblk0p2 ${DIR}/
  sudo mount -t tmpfs -o size=1m tmpfs ${DIR}/dev/
  sudo mount -t tmpfs -o size=1m tmpfs ${DIR}/tmp/
  sudo mount -t tmpfs -o size=1m tmpfs ${DIR}/var/log/
  sudo mount /dev/mmcblk0p1 ${DIR}/boot/
}

send_data() {
  rsync -avH --delete-during --delete-excluded --exclude-from=/root/backup/rsync-exclude ${DIR}/* $REMOTE:$BACKUP_PATH
}

post_backup() {
 for service in "${SERVICES_TO_STOP[@]}"; do
     docker start $service
   done
}

pre_backup
do_mounts
send_data
cleanup
post_backup